'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Article } from './apiCalls/apiCalls';
import { ArticlesContext } from './hooks/useArticles';
import { useEffect, useState } from 'react';
import { fetchTopNews } from './apiCalls/apiCalls';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'NewsApp',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [articles, setArticles] = useState<Article[]>([]);
  const [searchedArticles, setSearchedArticles] = useState<Article[]>([]);

  useEffect(() => {
    fetchTopNews().then((data) => {
      setArticles(data.articles);
    });
    setArticles(articles);
    //eslint-disable-next-line
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ArticlesContext.Provider value={{articles, setSearchedArticles, searchedArticles}} >{children}</ArticlesContext.Provider>
      </body>
    </html>
  );
}
